### ISSUE TITLE
Wildcard match

### ISSUE THREAD

**Issue by szepeviktor** [haraka/haraka-plugin-recipient-routes#11]
Could we use wildcards in email addresses?
```
[routes]
1*@example.com=lmtp://mail.example.com:2525
```
Thank you.

**Comment by msimerson** [comment]
You could, but I can't immediately think of a way to do it that wouldn't make this plugin an order of magnitude slower. It's super fast now because object property inspection is wicked fast in JS, even on very large objects. The same is certainly not true for regex evaluation.

I don't know that you'd be able to maintain the same "it works equally well in JS objects or redis backends" either. 

If you assemble a PR that doesn't injure performance and maintains the feature parity between memory and redis backends, I'll certain entertain it.
